Feature/calculator interaction
Nexters/Amoogye-iOS pull request #84
Opened 2019-09-03 06:32 UTC by tngusmiso

## Related Issue

resolve: #83 

## Description

- 인원, 재료 모드 인터렉션
![화면-기록-2019-09-03-오후-3 19 06](https://user-images.githubusercontent.com/37800715/64148958-9f386900-ce5f-11e9-8e42-ec105e68519e.gif)

2019-09-03 08:26 UTC, hihiboss approved these changes
매우 훌륭합니다!!

2019-09-03 08:26 UTC, hihiboss commented on Amoogye/Calculator/CalculatorViewController + interaction.swift
> +            mode = .PortionOnly
>참고
변수 이름을 그냥 `mode` 라고 하는 것보다 `currentMode`와 같이 조금 더 구체적인 이름이면 더 좋을 것 같음!

2019-09-09 16:50 UTC, hihiboss requested changes
Develop Pull 다시 해야합니당!!

2019-09-10 09:41 UTC, tngusmiso commented
확인해주세욤!! 드디어..

2019-09-10 20:25 UTC, hihiboss approved these changes

2019-09-10 20:25 UTC, merged